Add contact form with submission functionality
bookshop-projektarbete/bookshop-frontend pull request #15
Opened 2024-12-16 06:09 UTC by Julieanna97

- Added a responsive contact form to the contact.html page
- Included fields for name, email, phone, address, subject, and description
- Implemented form submission with validation
- Added success message display on successful submission
- Moved form styling to a separate custom-style.css file
- Created contact.js for handling form submission and success message

2024-12-16 08:28 UTC, sarahosterhed reviewed
Good job with the contact form and implementing different options! 👏🏻

One thing I see though is that you implemented bootstrap styling on the header and footer. In the beginning of the project, Linn created a script for the header and footer that we were supposed to use and link to and I think we should keep this on all pages to ensure that the design of these elements always look the same for consistency.

2024-12-16 08:30 UTC, linntarv reviewed
Looks good! Only thing is to import header from header.js so it looks the same on all pages

2024-12-16 08:30 UTC, linntarv commented on pages/contact.html
> +    <header class="d-flex justify-content-between align-items-center p-3">
Use common header, by importing <script src="header.js"></script>

2024-12-16 15:52 UTC, sarahosterhed requested changes
Good job with the contact form and implementing different options! 👏🏻

We discussed this card during the sprint review and didn't close this task because of three main reasons:
- The header and footer should be implemented from the scripts like on all the other pages to maintain consistency across the site.
- There are some tags/symbols missing in the code, so it would be good to validate it before we merge it.
- You are using bootstrap for the styling, but this is something that we should have discussed when initializing the project, if we wanted to use a framework for the styling. Now, all the other pages are styled with regular css and for best practice we agreed that all pages should be styled in the same way.

2024-12-16 17:21 UTC, Julieanna97 reviewed
> We discussed this card during the sprint review and didn't close it because of three main reasons:
> - The header and footer should be implemented from the scripts like on all the other pages to maintain consistency across the site.
> - There are some tags/symbols missing in the code, so it would be good to validate it before we merge it.
> - You are using bootstrap for the styling, but this is something that we should have discussed when initializing the project, if we wanted to use a framework for the styling. Now, all the other pages are styled with regular css and for best practice we agreed that all pages should be styled in the same way.
> 
> These issues would need to be adressed. 

Noted. :) I will change it to CSS.

2024-12-17 09:56 UTC, linntarv submitted a review, later dismissed
Looks great! Just remember to update the file paths to the js files that are now in the folder scripts :)

2024-12-17 09:56 UTC, linntarv commented on contact.html
> +    <script src="header.js"></script>
update file path, should be: scripts/header.js

2024-12-17 09:56 UTC, linntarv commented on contact.html
> +    <script src="footer.js"></script>
update these paths too: scripts/footer.js & scripts/contact.js

2024-12-18 14:18 UTC, mjp414 reviewed
Looks good! 
Just wondering if the footer is correct? It looks like the script is commented in the HTML-file and other coding has been added. Otherwise it looks good 🙂

2024-12-18 16:46 UTC, Julieanna97 commented
> Looks good! Just wondering if the footer is correct? It looks like the script is commented in the HTML-file and other coding has been added. Otherwise it looks good 🙂

Tried adding the script.js but the links are not clickable. So I added manually instead.

2024-12-18 19:59 UTC, merged