BS-44 fixed positioning for header + footer, added main container for…
bookshop-projektarbete/bookshop-frontend pull request #7
Opened 2024-12-12 14:32 UTC by linntarv

fixed positioning for header + footer
added main-container id to use for content on pages

2024-12-12 15:21 UTC, dantvi approved these changes
The code looks great!

2024-12-12 15:24 UTC, dantvi submitted a review, later dismissed

2024-12-13 08:10 UTC, sarahosterhed submitted a review, later dismissed
Going through the changes together with @linntarv and merging them

2024-12-13 08:12 UTC, merged

2024-12-13 08:36 UTC, Julieanna97 requested changes
Great work overall 👍